#!/bin/sh

MIRROR_DEBIAN="http://cdn.debian.net/debian/"
MIRROR_SECURITY="http://security.geo.debian.org/"

lh config noautoconfig \
        --apt-recommends false \
        --apt-secure false \
	--binary-filesystem fat32 \
	--archive-areas "main" \
	--distribution squeeze \
	--iso-publisher "Jun NOGATA; http://www.nofuture.tv/;" \
	--language ja \
	--mirror-binary ${MIRROR_DEBIAN} \
	--mirror-binary-security ${MIRROR_SECURITY} \
	--mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--syslinux-menu vesamenu \
	--syslinux-timeout 10 \
	--win32-loader false \
	${@}
